# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 761867a78ffdc37278d0252b649c3cf7fe5152d5f659685d3f15c91b063a3a5d82fcaed4ef9b4f7a82ae3665641940d003345b904cda692f0ea6305cac2a60e9

test:
  secret_key_base: 81f2b94123cf4461a0a980a0ea0608674c970b8145b5671df16e4595425fb755b43edb8c03aac1a5870288caacac701fe797198bc13b695d7ebe0daf1a9e4244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
